# Generated by Django 5.1 on 2024-08-27 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_product_product_akshira'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_akshira',
            name='Product_Price',
            field=models.IntegerField(default=0),
        ),
    ]
